#!/bin/bash -eu
# AVATAO_USER is defined in the Dockerfile, here.
# AVATAO_SECRET is set by CRP Docker.

if [ "$AVATAO_USER" != "$PAM_USER" ]; then
    exit 1
fi

if [ "$AVATAO_SECRET" != "$PAM_AUTHTOK" ]; then
    exit 1
fi

exit 0
